config/routes.rb
Grafy::Application.routes.draw do

  resources :graphs

end

app/models/stat_reader.rb
class StatReader

  def self.avg(file, column)
    merania = self.read(file, column)
    merania_fin = []
    (1...merania.count).each do |meranie|
      merania_fin << [meranie, merania[meranie][-1][0]]
    end
    binding.pry

    {-1 => merania_fin}
  end


  def self.read(file, column)

    merania=[]
    aktualne_meranie = []
    File.open(Rails.root + "app/assets/texts/" + file).each_line do |line|
      if /Meranie/.match line
        merania << aktualne_meranie
        aktualne_meranie = []
      else
        a = line.split ';'
        aktualne_meranie << [a[0].to_i, a[column].to_f]
      end


    end

    sum = 0
    merania_fin = []
    (1...merania.count).each do |meranie|
      merania_fin << [meranie, merania[meranie][-1][0]]
      sum+= merania[meranie][-1][0]
    end
    merania[-1] = merania_fin
    merania[-2] = sum/20.to_f

    merania
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController

  def index

    @texts = Dir.glob("app/assets/texts/*.txt")

    render 'index'
  end

  def show
    @texts = Dir.glob("app/assets/texts/*.txt")
    @file = params[:file]
    @id = params[:id].to_i

    @col = params[:col].to_i

    @merania = StatReader.read(@file, @col)


    render 'show'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/graphs/index.html.erb
<% @texts.each do |text| %>
    <p><%= link_to text, graph_path(0,:file => text.split('/')[-1], :col =>1) %></p>
<% end %>

app/views/graphs/show.html.erb
<%= javascript_include_tag "highcharts.js", "chartkick" %>
<% @texts.each do |text| %>
    &nbsp;&nbsp;&nbsp;&nbsp;
    <%= link_to   text.split('/')[-1], graph_path(0, :file => text.split('/')[-1], :col => 1) %>
<% end %>

<p><b>Maxima:</b></p>
<% @merania.each_with_index do |meranie, index| %>
    <%= link_to index, graph_path(index, :file => @file, :col => 1) %>
<% end %>
<%= link_to 'all', graph_path(-1, :file => @file, :col => 1) %>

<p><b>Priemery</b></p>
<% @merania.each_with_index do |meranie, index| %>
    <%= link_to index, graph_path(index, :file => @file, :col => 2) %>
<% end %>

<p>Priemer: <%= @merania[-2] %></p>

<%= column_chart @merania[@id] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grafy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>